# Generated by Django 5.1.1 on 2024-10-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_agendamento_pago_alter_agendamento_tipo_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
