# Generated by Django 5.1.1 on 2024-10-11 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_agendamento_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='produtos',
            field=models.ManyToManyField(blank=True, to='controle.produto'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_corte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.tipocorte'),
        ),
    ]
