# Generated by Django 5.1.1 on 2024-10-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_agendamento_produtos_alter_agendamento_tipo_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
