# Generated by Django 5.1.1 on 2024-10-22 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0007_remove_produto_quantidade_produto_estoque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.agendamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.produto')),
            ],
        ),
    ]
