# Generated by Django 5.1.1 on 2024-10-22 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0008_agendamentoproduto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgendamentoProduto',
        ),
    ]
