# Generated by Django 5.1.1 on 2024-10-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0010_barbeiro_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='tipo_corte',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='tipo_corte',
            field=models.ManyToManyField(to='controle.tipocorte'),
        ),
    ]
