# Generated by Django 5.1.1 on 2024-10-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0011_remove_agendamento_tipo_corte_agendamento_tipo_corte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbeiro',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
